### ISSUE TITLE
What does "registry": "jspm" do?

### ISSUE THREAD

**Issue by letmaik** [jspm/demo-es6#17]
This demo has `"registry": "jspm"` in package.json, however this doesn't exist in [another demo](https://github.com/codylindley/jspm-startup/blob/master/package.json). When is this needed and who reads that?

**Comment by guybedford** [comment]
See https://github.com/jspm/jspm-cli/blob/master/docs/publishing-packages.md#writing-a-library-or-application-for-usage-just-with-jspm for more info.

It allows simpler dependency forms in the `dependencies` object.

Then also when detecting if a package.json file is "jspm aware", we check for the existence of a "registry" or "jspm" property.

**Comment by letmaik** [comment]
Thanks, that helps.
