### ISSUE TITLE
How would I configure test.html to pull from a private NPM registry?

### ISSUE THREAD

**Issue by mattdsteele** [jspm/demo-es6#18]
My company has a self-hosted NPM registry and I'm looking to demo jspm with it; pulling down packages from our NPM as though it were a CDN. Is this possible? I've tried adding these lines to `config.js`:

```
  registries: {
    npm: {
      registry: 'http://private-registry.mycompany.com',
      handler: 'jspm-npm'
    }
  },
```

But it's still pulling from `npm.jspm.io` when I open `test.html`. Is what I'm looking to do feasible?

**Comment by guybedford** [comment]
@mattdsteele try following https://github.com/jspm/jspm-cli/blob/master/docs/registries.md#private-npm here. Let me know if you have any issues at all though.

**Comment by mattdsteele** [comment]
@guybedford It's reading from my `.npmrc` and I can `jspm install npm:private-package` fine. What I'm interested in doing is loading private NPM modules through a jspm.io-like CDN.

Here's my use case: We've created a number of components (mostly Angular directive) and persisted them to NPM. I'd like to create demo pages in our internal JSBin that showcase how to use these components. As such I'd like to be able to load NPM-hosted packages without a `jspm install` step.

Perhaps I'm asking the wrong question - would I need to host my own `npm.jspm.io`-style CDN to make this work?

**Comment by guybedford** [comment]
@mattdsteele yes exactly you'd need to host some form of internal jspm.io CDN. In jspm 0.17 this will be as simple as hosting jspm_packages with all your packages installed as a CDN location.

**Comment by mattdsteele** [comment]
I'll look into that and watch for 0.17, thanks!
