### ISSUE TITLE
jspm is not showing error detail when there was mistake in the code

### ISSUE THREAD

**Issue by jeud** [jspm/demo-es6#20]
I'm using jspm, it's working fine except so far it's not showing meaningful error when there was mistake in the code

_package.json_

``` json
{
  "devDependencies": {
    "jspm": "^0.16.19"
  },
  "jspm": {
    "dependencies": {
      "react": "npm:react@^0.14.3",
      "react-dom": "npm:react-dom@^0.14.3"
    },
    "devDependencies": {
      "babel": "npm:babel-core@^5.8.24",
      "babel-runtime": "npm:babel-runtime@^5.8.24",
      "core-js": "npm:core-js@^1.1.4"
    }
  }
}
```

_config.js_

``` javascript
System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  ...
});
```

For example if I made some mistake in the code e.g. `import xxx fro 'xxx';` or `class Foo exten Bar { }`, on the browser's console it only shown

![image](https://cloud.githubusercontent.com/assets/3884881/12448791/058e6fbe-bfab-11e5-8795-8f8a95b87b24.png)

Do I need some extra configurations?, please guide. Thanks

**Comment by jeud** [comment]
![Screen capture here](https://cloud.githubusercontent.com/assets/3884881/12448791/058e6fbe-bfab-11e5-8795-8f8a95b87b24.png)

**Comment by guybedford** [comment]
Click on the three dots at the end of the first line of the error message.

**Comment by jeud** [comment]
@guybedford , oh thanks, I was so stupid
