### ISSUE TITLE
jspm setmode

### ISSUE THREAD

**Issue by djindjic** [jspm/demo-es6#7]
Can you provide us (here or in jspm-cli repo) just a little more detailed documentatio for jspm setmode argument? For example, I have tried demo app with setmode local and without this command, and I can't see any different behavior.

**Comment by trusktr** [comment]
> does it make sense to have setmode with remote/local values, and new set_env command with production/development choise?

Yes, exactly what I just though in the gitter channel!

**Comment by trusktr** [comment]
> I think it may make more sense to distribute uncompiled ES6 and rather do building for production only.

Very much agreed.
